baseURL = "https://uwaang.github.io/"  # TODO: 수정
languageCode = "ko-kr"
title = "Uwaang's Blog"
theme = "PaperMod"
timeZone = "Asia/Seoul"

[pagination]
  pagerSize = 10

[params]
  author = "YOUR_NAME"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowReadingTime = true

[params.comments]
  enabled = true
  provider = "giscus"

  [params.comments.giscus]
    repo = "Uwaang/uwaang.github.io"
    repoID = "R_kgDOO-Vt-w"          # giscus ➜ "repo ID"
    category = "General"
    categoryID = "DIC_kwDOO-Vt-84Crs-Q"  # giscus ➜ "category ID"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "ko"

[markup]
  [markup.goldmark.renderer]
    unsafe = true 