baseURL = "https://uwaang.github.io/"  # TODO: 수정
languageCode = "ko-kr"
title = "Uwaang's Blog"
theme = "PaperMod"
timeZone = "Asia/Seoul"

[pagination]
  pagerSize = 10

[params]
  author = "YOUR_NAME"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  comments = true
  github_username = "Uwaang"  # GitHub 사용자명
  github_repo = "obsidian-hugo-blog"  # 리포지토리명

[params.giscus]
  repo = "Uwaang/uwaang.github.io"
  repoID = "R_kgDOO-Vt-w"
  category = "General"
  categoryID = "DIC_kwDOO-Vt-84Crs-Q"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "light"
  lang = "ko"

[markup]
  [markup.goldmark.renderer]
    unsafe = true 