[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.152.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  HUGO_BASEURL = "https://uwaang.netlify.app/"
  HUGO_VERSION = "0.152.0"

[context.deploy-preview.environment]
  HUGO_BASEURL = "https://deploy-preview-${REVIEW_ID}--uwaang.netlify.app/"
  HUGO_VERSION = "0.152.0"

[context.branch-deploy.environment]
  HUGO_BASEURL = "https://branch-${BRANCH}--uwaang.netlify.app/"
  HUGO_VERSION = "0.152.0" 